import subprocess, os, glob, json, base64, re
APP = '/Users/mosesjeremiah/boardroom dilema/app'
PUB = f'{APP}/public'
REPORT = []
def run(*cmd): subprocess.run(['ffmpeg', '-nostdin', '-v', 'error', '-y', *cmd], check=True)
def size(p): return os.path.getsize(p)
def dims(p):
    out = subprocess.run(['ffprobe','-v','error','-select_streams','v:0','-show_entries','stream=width,height','-of','csv=p=0',p],capture_output=True,text=True).stdout.strip()
    return [int(x) for x in out.split(',')[:2]]
def ssim(ref, test):
    r = subprocess.run(['ffmpeg','-nostdin','-v','info','-i',ref,'-i',test,'-lavfi','[1:v]scale=%d:%d:flags=lanczos[t];[0:v][t]ssim' % tuple(dims(ref)),'-f','null','-'],capture_output=True,text=True).stderr
    m = re.search(r'All:([0-9.]+)', r); return float(m.group(1)) if m else None

# 1) Photos: AVIF + WebP at full width and 1280 wide (never upscaled), plus a tiny blurred placeholder.
placeholders = {}
photos = sorted(glob.glob(f'{PUB}/scenes/*.jpg')) + sorted(glob.glob(f'{PUB}/evidence/*.jpg'))
for src in photos:
    stem = src[:-4]; w, h = dims(src)
    widths = [w] + ([1280] if w > 1400 else [])
    for tw in widths:
        suffix = '' if tw == w else f'-{tw}'
        scale = [] if tw == w else ['-vf', f'scale={tw}:-2:flags=lanczos']
        run('-i', src, *scale, '-c:v', 'libaom-av1', '-still-picture', '1', '-crf', '23', '-cpu-used', '4', '-pix_fmt', 'yuv420p', f'{stem}{suffix}.avif')
        run('-i', src, *scale, '-c:v', 'libwebp', '-quality', '86', '-compression_level', '6', f'{stem}{suffix}.webp')
    REPORT.append({'photo': os.path.relpath(src, PUB), 'jpg': size(src), 'avif': size(f'{stem}.avif'), 'webp': size(f'{stem}.webp'),
                   'ssim_avif': ssim(src, f'{stem}.avif'), 'ssim_webp': ssim(src, f'{stem}.webp')})
    if '/scenes/' in src:
        tiny = f'{stem}.lqip.webp'
        run('-i', src, '-vf', 'scale=32:-2:flags=area', '-c:v', 'libwebp', '-quality', '50', tiny)
        placeholders[os.path.basename(stem)] = 'data:image/webp;base64,' + base64.b64encode(open(tiny, 'rb').read()).decode()
        os.remove(tiny)
with open(f'{APP}/src/scenePlaceholders.ts', 'w') as f:
    f.write('// Generated by media/optimise_media.py — tiny blurred previews shown while each scene photo loads.\n')
    f.write('export const SCENE_PLACEHOLDERS: Record<string, string> = ' + json.dumps(placeholders, indent=2) + ';\n')

# 2) Voice: Opus (WebM) next to each MP3. Same mono speech, about a third of the size.
for src in sorted(glob.glob(f'{PUB}/voice/*.mp3')):
    out = src[:-4] + '.webm'
    run('-i', src, '-c:a', 'libopus', '-b:a', '48k', '-ac', '1', '-application', 'audio', out)
voice_mp3 = sum(size(p) for p in glob.glob(f'{PUB}/voice/*.mp3')); voice_webm = sum(size(p) for p in glob.glob(f'{PUB}/voice/*.webm'))
REPORT.append({'voice_mp3_total': voice_mp3, 'voice_opus_total': voice_webm})

# 3) Films: a 480p rendition for slow connections (720p stays the default) and a poster frame for each.
for src in sorted(glob.glob(f'{PUB}/films/*.mp4')):
    if src.endswith('_480.mp4'): continue
    stem = src[:-4]
    run('-i', src, '-vf', 'scale=-2:480:flags=lanczos', '-c:v', 'libx264', '-preset', 'slow', '-crf', '24', '-maxrate', '750k', '-bufsize', '1500k',
        '-profile:v', 'main', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-b:a', '96k', '-movflags', '+faststart', f'{stem}_480.mp4')
    run('-ss', '1.2', '-i', src, '-frames:v', '1', '-c:v', 'libwebp', '-quality', '80', f'{stem}_poster.webp')
    REPORT.append({'film': os.path.basename(src), 'mp4_720': size(src), 'mp4_480': size(f'{stem}_480.mp4'), 'poster': size(f'{stem}_poster.webp')})

json.dump(REPORT, open('/private/tmp/claude-501/-Users-mosesjeremiah-boardroom-dilema/e4e491a0-b456-4f45-81da-8c2754e8ae4f/scratchpad/optimise/report.json', 'w'), indent=1)
print('ENCODE DONE')
