// Generated by media/optimise_media.py — AVIF (and, where smaller than the JPEG, WebP) variants for each photo in public/.
export const IMAGE_VARIANTS: Record<string, { width: number; height: number; avif: [number, string][]; webp: [number, string][] }> = {
  "evidence/doc_incident_photo.jpg": {
    "width": 1200,
    "height": 675,
    "avif": [
      [
        1200,
        "evidence/doc_incident_photo.avif"
      ]
    ],
    "webp": [
      [
        1200,
        "evidence/doc_incident_photo.webp"
      ]
    ]
  },
  "evidence/doc_near_miss_photo.jpg": {
    "width": 1200,
    "height": 675,
    "avif": [
      [
        1200,
        "evidence/doc_near_miss_photo.avif"
      ]
    ],
    "webp": [
      [
        1200,
        "evidence/doc_near_miss_photo.webp"
      ]
    ]
  },
  "evidence/doc_news_photo.jpg": {
    "width": 1200,
    "height": 675,
    "avif": [
      [
        1200,
        "evidence/doc_news_photo.avif"
      ]
    ],
    "webp": []
  },
  "evidence/newsprint.jpg": {
    "width": 900,
    "height": 1200,
    "avif": [
      [
        900,
        "evidence/newsprint.avif"
      ]
    ],
    "webp": []
  },
  "scenes/accountability.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/accountability-1280.avif"
      ],
      [
        2048,
        "scenes/accountability.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/accountability-1280.webp"
      ],
      [
        2048,
        "scenes/accountability.webp"
      ]
    ]
  },
  "scenes/board_qa.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/board_qa-1280.avif"
      ],
      [
        2048,
        "scenes/board_qa.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/board_qa-1280.webp"
      ],
      [
        2048,
        "scenes/board_qa.webp"
      ]
    ]
  },
  "scenes/boardcase.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/boardcase-1280.avif"
      ],
      [
        2048,
        "scenes/boardcase.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/boardcase-1280.webp"
      ],
      [
        2048,
        "scenes/boardcase.webp"
      ]
    ]
  },
  "scenes/crisis.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/crisis-1280.avif"
      ],
      [
        2048,
        "scenes/crisis.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/crisis-1280.webp"
      ],
      [
        2048,
        "scenes/crisis.webp"
      ]
    ]
  },
  "scenes/desk.jpg": {
    "width": 2560,
    "height": 1440,
    "avif": [
      [
        1280,
        "scenes/desk-1280.avif"
      ],
      [
        2560,
        "scenes/desk.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/desk-1280.webp"
      ],
      [
        2560,
        "scenes/desk.webp"
      ]
    ]
  },
  "scenes/employee.jpg": {
    "width": 1200,
    "height": 800,
    "avif": [
      [
        1200,
        "scenes/employee.avif"
      ]
    ],
    "webp": [
      [
        1200,
        "scenes/employee.webp"
      ]
    ]
  },
  "scenes/employee_bg.jpg": {
    "width": 1600,
    "height": 900,
    "avif": [
      [
        1280,
        "scenes/employee_bg-1280.avif"
      ],
      [
        1600,
        "scenes/employee_bg.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/employee_bg-1280.webp"
      ],
      [
        1600,
        "scenes/employee_bg.webp"
      ]
    ]
  },
  "scenes/executive.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/executive-1280.avif"
      ],
      [
        2048,
        "scenes/executive.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/executive-1280.webp"
      ],
      [
        2048,
        "scenes/executive.webp"
      ]
    ]
  },
  "scenes/family.jpg": {
    "width": 1200,
    "height": 800,
    "avif": [
      [
        1200,
        "scenes/family.avif"
      ]
    ],
    "webp": [
      [
        1200,
        "scenes/family.webp"
      ]
    ]
  },
  "scenes/family_bg.jpg": {
    "width": 1600,
    "height": 900,
    "avif": [
      [
        1280,
        "scenes/family_bg-1280.avif"
      ],
      [
        1600,
        "scenes/family_bg.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/family_bg-1280.webp"
      ],
      [
        1600,
        "scenes/family_bg.webp"
      ]
    ]
  },
  "scenes/intro.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/intro-1280.avif"
      ],
      [
        2048,
        "scenes/intro.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/intro-1280.webp"
      ],
      [
        2048,
        "scenes/intro.webp"
      ]
    ]
  },
  "scenes/journalist.jpg": {
    "width": 1200,
    "height": 800,
    "avif": [
      [
        1200,
        "scenes/journalist.avif"
      ]
    ],
    "webp": [
      [
        1200,
        "scenes/journalist.webp"
      ]
    ]
  },
  "scenes/journalist_bg.jpg": {
    "width": 1600,
    "height": 900,
    "avif": [
      [
        1280,
        "scenes/journalist_bg-1280.avif"
      ],
      [
        1600,
        "scenes/journalist_bg.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/journalist_bg-1280.webp"
      ],
      [
        1600,
        "scenes/journalist_bg.webp"
      ]
    ]
  },
  "scenes/outcome.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/outcome-1280.avif"
      ],
      [
        2048,
        "scenes/outcome.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/outcome-1280.webp"
      ],
      [
        2048,
        "scenes/outcome.webp"
      ]
    ]
  },
  "scenes/regulator.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/regulator-1280.avif"
      ],
      [
        2048,
        "scenes/regulator.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/regulator-1280.webp"
      ],
      [
        2048,
        "scenes/regulator.webp"
      ]
    ]
  },
  "scenes/role.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/role-1280.avif"
      ],
      [
        2048,
        "scenes/role.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/role-1280.webp"
      ],
      [
        2048,
        "scenes/role.webp"
      ]
    ]
  },
  "scenes/tabletop.jpg": {
    "width": 2048,
    "height": 1157,
    "avif": [
      [
        1280,
        "scenes/tabletop-1280.avif"
      ],
      [
        2048,
        "scenes/tabletop.avif"
      ]
    ],
    "webp": [
      [
        1280,
        "scenes/tabletop-1280.webp"
      ],
      [
        2048,
        "scenes/tabletop.webp"
      ]
    ]
  }
};
